version: "3.2"

services:

  api:
    build:
      context: .
    image: grover-engineering-recruitment
    container_name: grover-engineering-recruitment-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal

  products:
    build:
      context: .
    image: grover-engineering-recruitment
    container_name: grover-engineering-recruitment-products
    env_file: docker-compose.env
    environment:
      SERVICES: products
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
    networks:
      - internal

  products-db:
    build:
      context: .
    image: grover-engineering-recruitment
    container_name: grover-engineering-recruitment-products-db
    env_file: docker-compose.env
    environment:
      SERVICES: products-db
    labels:
      - "traefik.enable=false"
    links:
      - nats
      - pg
    depends_on:
      - nats
      - pg
    networks:
      - internal

  nats:
    image: nats
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  pg:
    image: postgres
    container_name: db
    env_file: docker-compose.env
    ports:
      - "5432:5432"
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - internal
      - default

networks:
  internal:
